# Generated by Django 4.2 on 2023-04-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_rename_user_pet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('DO', 'Dog'), ('CA', 'Cat'), ('CO', 'Cow'), ('PI', 'Pig'), ('HO', 'Horse'), ('GP', 'Guinea Pig'), ('HA', 'Hamster'), ('RA', 'Rabbit'), ('FE', 'Ferret'), ('TU', 'Turtle'), ('LI', 'Lizard'), ('SP', 'Spider'), ('SC', 'Scorpio')], max_length=2),
        ),
    ]
